version: "3.8"

networks:
  dev:
    driver: bridge

services:
  company_structure:
    depends_on:
      - "company_structure_mongodb"
    container_name: company_structure_services
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ~/.aspnet/https:/https/
      - ~/application/logs/api:/app/Logs
    restart: always
    build:
      context: .
      dockerfile: Brusnika.Api/Dockerfile
    environment:
      #      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.crt
      #      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/privkey.key
      - MongoDbSettings__ConnectionString=mongodb://${MONGODB_DEFAULT_USER}:${MONGODB_DEFAULT_PASS}@company_structure_mongodb:27017
      - ASPNETCORE_URLS=http://+:80
      #  https://+:443;
      #- ASPNETCORE_HTTPS_PORT=8443
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=password
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Protocols=Http1AndHttp2
    networks:
      - dev

  company_structure_mongodb:
    image: mongo:7.0.2
    container_name: company_structure_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DEFAULT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DEFAULT_PASS}
      MONGO_INITDB_ROOT_DATABASE: company_structure
    restart: always
    ports:
      - "27017"
    volumes:
      - ~/application/data/mongo/db:/data/db
    networks: 
      - dev